// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDjX0axCOacct4w7EFtu9ni_YciItyVrYE',
    appId: '1:651410024452:web:ee13ab594e077002e22d51',
    messagingSenderId: '651410024452',
    projectId: 'campus-bike-rental-491203',
    authDomain: 'campus-bike-rental-491203.firebaseapp.com',
    storageBucket: 'campus-bike-rental-491203.firebasestorage.app',
    measurementId: 'G-BQ383VH1N4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDVT9lkyjRasuvAcJGHIX4uAOwkIUWjqDY',
    appId: '1:651410024452:android:b6bcd8bc7be2212ae22d51',
    messagingSenderId: '651410024452',
    projectId: 'campus-bike-rental-491203',
    storageBucket: 'campus-bike-rental-491203.firebasestorage.app',
  );
}
